services:
  db:
    image: postgres:15
    container_name: flask_postgres
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flask_network

volumes:
  db_data:

networks:
  flask_network:
