"""Changed Container Model to have fk with available models model

Revision ID: 3c87e73c816f
Revises: 0e880d1de9a9
Create Date: 2025-01-20 11:18:58.088880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c87e73c816f'
down_revision = '0e880d1de9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_model_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'available_models', ['available_model_id'], ['id'])
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('available_model_id')

    # ### end Alembic commands ###
