"""changed user id to int

Revision ID: 92c95df1818f
Revises: 69fa1bf80bce
Create Date: 2025-01-20 14:56:42.252413

"""

from alembic import op
import sqlalchemy as sa

"""changed user id to int

Revision ID: 92c95df1818f
Revises: 69fa1bf80bce
Create Date: 2025-01-20 14:56:42.252413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92c95df1818f"
down_revision = "69fa1bf80bce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("containers", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.UUID(),
            type_=sa.Integer(),
            postgresql_using="CAST(REPLACE(user_id::text, '-', '')::bit(64)::bigint AS INTEGER)",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("containers", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.Integer(),
            type_=sa.UUID(),
            postgresql_using="uuid_generate_v4()",  # This will generate new UUIDs since we can't recover the original ones
            existing_nullable=False,
        )

    # ### end Alembic commands ###
